<?php

namespace Cuitcode\Paystack\Utils;

class ObjectTypes
{
    /**
     * @var array Mapping from object types to resource classes
     */
    const mapping = [
        // \Cuitcode\Paystack\Account::OBJECT_NAME => \Cuitcode\Paystack\Account::class,
        // \Cuitcode\Paystack\AccountLink::OBJECT_NAME => \Cuitcode\Paystack\AccountLink::class,
        // \Cuitcode\Paystack\AlipayAccount::OBJECT_NAME => \Cuitcode\Paystack\AlipayAccount::class,
        // \Cuitcode\Paystack\ApplePayDomain::OBJECT_NAME => \Cuitcode\Paystack\ApplePayDomain::class,
        // \Cuitcode\Paystack\ApplicationFee::OBJECT_NAME => \Cuitcode\Paystack\ApplicationFee::class,
        // \Cuitcode\Paystack\ApplicationFeeRefund::OBJECT_NAME => \Cuitcode\Paystack\ApplicationFeeRefund::class,
        // \Cuitcode\Paystack\Balance::OBJECT_NAME => \Cuitcode\Paystack\Balance::class,
        // \Cuitcode\Paystack\BalanceTransaction::OBJECT_NAME => \Cuitcode\Paystack\BalanceTransaction::class,
        // \Cuitcode\Paystack\BankAccount::OBJECT_NAME => \Cuitcode\Paystack\BankAccount::class,
        // \Cuitcode\Paystack\BillingPortal\Session::OBJECT_NAME => \Cuitcode\Paystack\BillingPortal\Session::class,
        // \Cuitcode\Paystack\BitcoinReceiver::OBJECT_NAME => \Cuitcode\Paystack\BitcoinReceiver::class,
        // \Cuitcode\Paystack\BitcoinTransaction::OBJECT_NAME => \Cuitcode\Paystack\BitcoinTransaction::class,
        // \Cuitcode\Paystack\Capability::OBJECT_NAME => \Cuitcode\Paystack\Capability::class,
        // \Cuitcode\Paystack\Card::OBJECT_NAME => \Cuitcode\Paystack\Card::class,
        // \Cuitcode\Paystack\Charge::OBJECT_NAME => \Cuitcode\Paystack\Charge::class,
        // \Cuitcode\Paystack\Checkout\Session::OBJECT_NAME => \Cuitcode\Paystack\Checkout\Session::class,
        // \Cuitcode\Paystack\Collection::OBJECT_NAME => \Cuitcode\Paystack\Collection::class,
        // \Cuitcode\Paystack\CountrySpec::OBJECT_NAME => \Cuitcode\Paystack\CountrySpec::class,
        // \Cuitcode\Paystack\Coupon::OBJECT_NAME => \Cuitcode\Paystack\Coupon::class,
        // \Cuitcode\Paystack\CreditNote::OBJECT_NAME => \Cuitcode\Paystack\CreditNote::class,
        // \Cuitcode\Paystack\CreditNoteLineItem::OBJECT_NAME => \Cuitcode\Paystack\CreditNoteLineItem::class,
        \Cuitcode\Paystack\Customer::OBJECT_NAME => \Cuitcode\Paystack\Customer::class,
        // \Cuitcode\Paystack\CustomerBalanceTransaction::OBJECT_NAME => \Cuitcode\Paystack\CustomerBalanceTransaction::class,
        // \Cuitcode\Paystack\Discount::OBJECT_NAME => \Cuitcode\Paystack\Discount::class,
        // \Cuitcode\Paystack\Dispute::OBJECT_NAME => \Cuitcode\Paystack\Dispute::class,
        // \Cuitcode\Paystack\EphemeralKey::OBJECT_NAME => \Cuitcode\Paystack\EphemeralKey::class,
        // \Cuitcode\Paystack\Event::OBJECT_NAME => \Cuitcode\Paystack\Event::class,
        // \Cuitcode\Paystack\ExchangeRate::OBJECT_NAME => \Cuitcode\Paystack\ExchangeRate::class,
        // \Cuitcode\Paystack\File::OBJECT_NAME => \Cuitcode\Paystack\File::class,
        // \Cuitcode\Paystack\File::OBJECT_NAME_ALT => \Cuitcode\Paystack\File::class,
        // \Cuitcode\Paystack\FileLink::OBJECT_NAME => \Cuitcode\Paystack\FileLink::class,
        // \Cuitcode\Paystack\Invoice::OBJECT_NAME => \Cuitcode\Paystack\Invoice::class,
        // \Cuitcode\Paystack\InvoiceItem::OBJECT_NAME => \Cuitcode\Paystack\InvoiceItem::class,
        // \Cuitcode\Paystack\InvoiceLineItem::OBJECT_NAME => \Cuitcode\Paystack\InvoiceLineItem::class,
        // \Cuitcode\Paystack\Issuing\Authorization::OBJECT_NAME => \Cuitcode\Paystack\Issuing\Authorization::class,
        // \Cuitcode\Paystack\Issuing\Card::OBJECT_NAME => \Cuitcode\Paystack\Issuing\Card::class,
        // \Cuitcode\Paystack\Issuing\CardDetails::OBJECT_NAME => \Cuitcode\Paystack\Issuing\CardDetails::class,
        // \Cuitcode\Paystack\Issuing\Cardholder::OBJECT_NAME => \Cuitcode\Paystack\Issuing\Cardholder::class,
        // \Cuitcode\Paystack\Issuing\Dispute::OBJECT_NAME => \Cuitcode\Paystack\Issuing\Dispute::class,
        // \Cuitcode\Paystack\Issuing\Transaction::OBJECT_NAME => \Cuitcode\Paystack\Issuing\Transaction::class,
        // \Cuitcode\Paystack\LineItem::OBJECT_NAME => \Cuitcode\Paystack\LineItem::class,
        // \Cuitcode\Paystack\LoginLink::OBJECT_NAME => \Cuitcode\Paystack\LoginLink::class,
        // \Cuitcode\Paystack\Mandate::OBJECT_NAME => \Cuitcode\Paystack\Mandate::class,
        // \Cuitcode\Paystack\Order::OBJECT_NAME => \Cuitcode\Paystack\Order::class,
        // \Cuitcode\Paystack\OrderItem::OBJECT_NAME => \Cuitcode\Paystack\OrderItem::class,
        // \Cuitcode\Paystack\OrderReturn::OBJECT_NAME => \Cuitcode\Paystack\OrderReturn::class,
        // \Cuitcode\Paystack\PaymentIntent::OBJECT_NAME => \Cuitcode\Paystack\PaymentIntent::class,
        // \Cuitcode\Paystack\PaymentMethod::OBJECT_NAME => \Cuitcode\Paystack\PaymentMethod::class,
        // \Cuitcode\Paystack\Payout::OBJECT_NAME => \Cuitcode\Paystack\Payout::class,
        // \Cuitcode\Paystack\Person::OBJECT_NAME => \Cuitcode\Paystack\Person::class,
        \Cuitcode\Paystack\Plan::OBJECT_NAME => \Cuitcode\Paystack\Plan::class,
        // \Cuitcode\Paystack\Price::OBJECT_NAME => \Cuitcode\Paystack\Price::class,
        // \Cuitcode\Paystack\Product::OBJECT_NAME => \Cuitcode\Paystack\Product::class,
        // \Cuitcode\Paystack\Radar\EarlyFraudWarning::OBJECT_NAME => \Cuitcode\Paystack\Radar\EarlyFraudWarning::class,
        // \Cuitcode\Paystack\Radar\ValueList::OBJECT_NAME => \Cuitcode\Paystack\Radar\ValueList::class,
        // \Cuitcode\Paystack\Radar\ValueListItem::OBJECT_NAME => \Cuitcode\Paystack\Radar\ValueListItem::class,
        // \Cuitcode\Paystack\Recipient::OBJECT_NAME => \Cuitcode\Paystack\Recipient::class,
        // \Cuitcode\Paystack\RecipientTransfer::OBJECT_NAME => \Cuitcode\Paystack\RecipientTransfer::class,
        // \Cuitcode\Paystack\Refund::OBJECT_NAME => \Cuitcode\Paystack\Refund::class,
        // \Cuitcode\Paystack\Reporting\ReportRun::OBJECT_NAME => \Cuitcode\Paystack\Reporting\ReportRun::class,
        // \Cuitcode\Paystack\Reporting\ReportType::OBJECT_NAME => \Cuitcode\Paystack\Reporting\ReportType::class,
        // \Cuitcode\Paystack\Review::OBJECT_NAME => \Cuitcode\Paystack\Review::class,
        // \Cuitcode\Paystack\SetupIntent::OBJECT_NAME => \Cuitcode\Paystack\SetupIntent::class,
        // \Cuitcode\Paystack\Sigma\ScheduledQueryRun::OBJECT_NAME => \Cuitcode\Paystack\Sigma\ScheduledQueryRun::class,
        // \Cuitcode\Paystack\SKU::OBJECT_NAME => \Cuitcode\Paystack\SKU::class,
        // \Cuitcode\Paystack\Source::OBJECT_NAME => \Cuitcode\Paystack\Source::class,
        // \Cuitcode\Paystack\SourceTransaction::OBJECT_NAME => \Cuitcode\Paystack\SourceTransaction::class,
        // \Cuitcode\Paystack\Subscription::OBJECT_NAME => \Cuitcode\Paystack\Subscription::class,
        // \Cuitcode\Paystack\SubscriptionItem::OBJECT_NAME => \Cuitcode\Paystack\SubscriptionItem::class,
        // \Cuitcode\Paystack\SubscriptionSchedule::OBJECT_NAME => \Cuitcode\Paystack\SubscriptionSchedule::class,
        // \Cuitcode\Paystack\TaxId::OBJECT_NAME => \Cuitcode\Paystack\TaxId::class,
        // \Cuitcode\Paystack\TaxRate::OBJECT_NAME => \Cuitcode\Paystack\TaxRate::class,
        // \Cuitcode\Paystack\Terminal\ConnectionToken::OBJECT_NAME => \Cuitcode\Paystack\Terminal\ConnectionToken::class,
        // \Cuitcode\Paystack\Terminal\Location::OBJECT_NAME => \Cuitcode\Paystack\Terminal\Location::class,
        // \Cuitcode\Paystack\Terminal\Reader::OBJECT_NAME => \Cuitcode\Paystack\Terminal\Reader::class,
        // \Cuitcode\Paystack\ThreeDSecure::OBJECT_NAME => \Cuitcode\Paystack\ThreeDSecure::class,
        // \Cuitcode\Paystack\Token::OBJECT_NAME => \Cuitcode\Paystack\Token::class,
        // \Cuitcode\Paystack\Topup::OBJECT_NAME => \Cuitcode\Paystack\Topup::class,
        // \Cuitcode\Paystack\Transfer::OBJECT_NAME => \Cuitcode\Paystack\Transfer::class,
        // \Cuitcode\Paystack\TransferReversal::OBJECT_NAME => \Cuitcode\Paystack\TransferReversal::class,
        // \Cuitcode\Paystack\UsageRecord::OBJECT_NAME => \Cuitcode\Paystack\UsageRecord::class,
        // \Cuitcode\Paystack\UsageRecordSummary::OBJECT_NAME => \Cuitcode\Paystack\UsageRecordSummary::class,
        // \Cuitcode\Paystack\WebhookEndpoint::OBJECT_NAME => \Cuitcode\Paystack\WebhookEndpoint::class,
    ];
}